"""
Unified FAQ Service that orchestrates KnowledgeService and GeminiFaqService.
Provides a hybrid approach with caching and enhanced fallback responses.
"""

import hashlib
import time
from typing import Optional, Dict, Any
from app.services.knowledge_service import KnowledgeService
from app.services.gemini_faq_service import GeminiFaqService
from app.core.config import settings
from app.utils.logger import debug_log
from app.utils.language_detector import detect_language
from app.utils.bilingual_responses import t


class FaqService:
    """Unified FAQ service combining rule-based and AI-powered FAQ answering."""

    def __init__(self):
        self.knowledge_service = KnowledgeService(
            max_question_length=settings.max_question_length
        )
        self.gemini_service = GeminiFaqService() if settings.enable_gemini_faq else None

        # In-memory cache for KnowledgeService responses
        self.kb_cache: Dict[str, tuple[str, float]] = {}
        self.kb_cache_ttl = 3600  # 1 hour

    def _normalize_question(self, question: str) -> str:
        """Normalize question for cache key."""
        return hashlib.md5(question.lower().strip().encode()).hexdigest()

    def _get_kb_from_cache(self, normalized_question: str) -> Optional[str]:
        """Get KnowledgeService answer from cache if not expired."""
        if normalized_question in self.kb_cache:
            answer, timestamp = self.kb_cache[normalized_question]
            if time.time() - timestamp < self.kb_cache_ttl:
                debug_log("FAQ_KB_CACHE_HIT", normalized_question[:16])
                return answer
            else:
                del self.kb_cache[normalized_question]
        return None

    def _set_kb_cache(self, normalized_question: str, answer: str):
        """Store KnowledgeService answer in cache."""
        self.kb_cache[normalized_question] = (answer, time.time())
        debug_log("FAQ_KB_CACHE_SET", normalized_question[:16])

    def _cleanup_kb_cache_if_needed(self):
        """Clean up KB cache if it exceeds maximum size."""
        max_cache_size = 1000
        if len(self.kb_cache) > max_cache_size:
            # Remove oldest 20% of entries
            sorted_entries = sorted(self.kb_cache.items(), key=lambda x: x[1][1])
            to_remove = int(max_cache_size * 0.2)
            for key, _ in sorted_entries[:to_remove]:
                del self.kb_cache[key]
            debug_log("FAQ_KB_CACHE_SIZE_LIMIT", f"Removed {to_remove} oldest entries")

    async def answer(self, question: str, lang: str = None) -> str:
        """
        Answer FAQ question using hybrid approach.

        Args:
            question: User's question
            lang: Language code ('ar' or 'en'). If None, auto-detect.

        Returns:
            Answer from KnowledgeService or Gemini, or fallback message
        """
        # Detect language if not provided
        if lang is None:
            lang = detect_language(question)
        debug_log("FAQ_LANGUAGE", f"Detected: {lang}")

        normalized_q = self._normalize_question(question)

        # 1. Try KnowledgeService cache first
        kb_cached = self._get_kb_from_cache(normalized_q)
        if kb_cached:
            return kb_cached

        # 2. Try KnowledgeService
        kb_answer = self.knowledge_service.find_answer(question, lang)
        if kb_answer:
            self._set_kb_cache(normalized_q, kb_answer)
            self._cleanup_kb_cache_if_needed()
            debug_log("FAQ_KB_SUCCESS", "Answer found in knowledge base")
            return kb_answer

        debug_log("FAQ_KB_MISS", "No answer in knowledge base")

        # 3. Try Gemini if enabled
        if self.gemini_service:
            gemini_answer = await self.gemini_service.generate_answer(question)
            if gemini_answer:
                debug_log("FAQ_GEMINI_SUCCESS", "Answer generated by Gemini")
                return gemini_answer

            debug_log("FAQ_GEMINI_FAIL", "Gemini failed to generate answer")

        # 4. Final fallback with suggestions
        return self._fallback_response(lang)

    def _fallback_response(self, lang: str) -> str:
        """Generate fallback response with helpful suggestions."""
        base_message = t("FAQ_NO_ANSWER", lang)

        # Add helpful context
        if lang == "ar":
            suggestions = "يمكنني مساعدتك في البحث عن سكن. أخبرني بالمدينة والميزانية."
        else:
            suggestions = "I can help you search for housing. Tell me the city and budget."

        return f"{base_message} {suggestions}"

    def get_stats(self) -> Dict[str, Any]:
        """Get service statistics."""
        stats = {
            "kb_cache_size": len(self.kb_cache),
            "kb_cache_ttl": self.kb_cache_ttl,
        }

        if self.gemini_service:
            stats["gemini"] = self.gemini_service.get_stats()

        return stats
