services:
  - type: web
    name: staymatch-ai-service
    env: python
    rootDir: staymatch-ai-service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: groq_api_key
        sync: false
      - key: db_host
        sync: false
      - key: db_port
        sync: false
      - key: db_name
        sync: false
      - key: db_user
        sync: false
      - key: db_password
        sync: false